[package]
name = "elite-dangerous-static-data-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
csv = "1"

[dev-dependencies]
convert_case = "0.7.1"